# Generated by Django 4.2.1 on 2023-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idoCollage',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
