# Generated by Django 4.2.4 on 2023-08-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_idocollage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['gpa', 'name']},
        ),
    ]
