# Generated by Django 4.2.4 on 2023-08-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='idoCollage',
            new_name='collegeID',
        ),
    ]
