# Generated by Django 4.2.1 on 2023-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gender', models.CharField(max_length=6)),
                ('level', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
